services:
  qgis:
    image: qgis/qgis:${QGIS_VERSION}
    container_name: qgis
    volumes:
      - ../wtyczka_qgis_app:/tests_directory/wtyczka_qgis_app
    environment:
      # - DISPLAY=unix$DISPLAY
      - CI=True
      - DISPLAY=:99