name: Tests 🎳

on:
  push:
    branches:
      - main
    paths:
      - 'wtyczka_qgis_app_2/**'
      - '.docker/**'

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .docker
    strategy:
      matrix:
        qgis_version: [
          "release-3_34",
          "release-3_28",
        ]
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Make env
        run: cd .. && make env QGIS_VERSION=${{ matrix.qgis_version }}

      - name: Uruchomienie docker compose
        run: ./start.sh

      - name: Uruchomienie testów
        run: ./exec.sh
